# Importing Libraries

In [4]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import scipy.optimize as opt
import matplotlib.pyplot as plt
import pylab as pl
%matplotlib inline

# importing data

In [6]:
churn_df=pd.read_csv("ChurnData.csv")
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [7]:
churn_df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

# making churn as int:

In [9]:
churn_df=churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless','churn']]
churn_df["churn"]=churn_df["churn"].astype(int)
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

# Making X:

In [16]:
x=np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',   'callcard', 'wireless']])
x[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.]])

# Making Y:

In [15]:
y=np.asarray(churn_df["churn"])
y[0:5]

array([1, 1, 0, 0, 0])

# standarizing dataset

In [19]:
X=preprocessing.StandardScaler().fit(x).transform(x)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148]])

# Training and Testing set

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)

# Logistic Regression model

In [22]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(C=0.01,solver="sag").fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='sag')

In [23]:
#prediction

In [25]:
pr=LR.predict(x_test)
pr[0:5]

array([0, 0, 0, 0, 0])

In [26]:
#predicting probability

In [28]:
pb=LR.predict_proba(x_test)
pb

array([[0.7594836 , 0.2405164 ],
       [0.74869112, 0.25130888],
       [0.71031144, 0.28968856],
       [0.82046788, 0.17953212],
       [0.7132239 , 0.2867761 ],
       [0.76485242, 0.23514758],
       [0.67452711, 0.32547289],
       [0.74755063, 0.25244937],
       [0.57064293, 0.42935707],
       [0.77150972, 0.22849028],
       [0.73477563, 0.26522437],
       [0.77304493, 0.22695507],
       [0.69798871, 0.30201129],
       [0.58735407, 0.41264593],
       [0.83946931, 0.16053069],
       [0.70890839, 0.29109161],
       [0.67873154, 0.32126846],
       [0.64654178, 0.35345822],
       [0.65129061, 0.34870939],
       [0.73969235, 0.26030765],
       [0.69674594, 0.30325406],
       [0.68930199, 0.31069801],
       [0.82382747, 0.17617253],
       [0.68491589, 0.31508411],
       [0.66636911, 0.33363089],
       [0.86732974, 0.13267026],
       [0.64307521, 0.35692479],
       [0.68291574, 0.31708426],
       [0.66851149, 0.33148851],
       [0.87128693, 0.12871307],
       [0.

# Evalution

In [31]:
from sklearn.metrics import confusion_matrix,log_loss,jaccard_score,classification_report

In [32]:
jaccard_score(y_test,pr,pos_label=0)

0.625

In [33]:
confusion_matrix(y_test,pr,labels=[0,1])

array([[25,  0],
       [15,  0]], dtype=int64)

In [34]:
print(classification_report(y_test,pr))

              precision    recall  f1-score   support

           0       0.62      1.00      0.77        25
           1       0.00      0.00      0.00        15

    accuracy                           0.62        40
   macro avg       0.31      0.50      0.38        40
weighted avg       0.39      0.62      0.48        40



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
log_loss(y_test,pb)

0.6197680168380044